[functions.make-server-f0a9c31f]
verify_jwt = false
cors_origins = [
  "http://localhost:3000",
  "http://localhost:5173",
  "https://apex-auto-movers.vercel.app",
]
cors_methods = ["GET", "POST", "PATCH", "OPTIONS"]
cors_headers = [
  "Content-Type",
  "Authorization",
  "apikey",
  "x-client-info",
  "x-supabase-api-version",
]

