/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bcjoptzhizulftdxewaj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjam9wdHpoaXp1bGZ0ZHhld2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NzM1NTEsImV4cCI6MjA3NjI0OTU1MX0.n5oD9WAV-tEHebfFceBw0BiUgChc2UT74Hv--G5qIwg"